export type RfpStatus = 'RELEASED' | 'APPROVED' | 'DRAFT' | 'VOID';

export interface RfpMonitoringRecord {
  expectedSeries: string;
  cwrProcessed: string;
  cwrUsage: number;
  trampsysStatus: RfpStatus;
  statusCwr: string;
  remarksCwr: string;
  etaTrampsys: string;
  etdTrampsys: string;
  payeePerTrampsys: string;
  vessel: string;
  voy: string;
  port: string;
  series: string;
  currencyInCwr: string;
  amountInCwr: number | null;
}

/**
 * Dummy data based on the shared spreadsheet columns.
 */
export const rfpMonitoringData: RfpMonitoringRecord[] = [
  {
    expectedSeries: '13170',
    cwrProcessed: 'eRFP13170',
    cwrUsage: 1,
    trampsysStatus: 'RELEASED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13170',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13171',
    cwrProcessed: 'eRFP13171',
    cwrUsage: 1,
    trampsysStatus: 'RELEASED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13171',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13172',
    cwrProcessed: 'eRFP13172',
    cwrUsage: 1,
    trampsysStatus: 'RELEASED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13172',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13173',
    cwrProcessed: 'eRFP13173',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'MANILA HARBOR CENTER PORT & SERVICES INC',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13173',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13174',
    cwrProcessed: 'eRFP13174',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'MANILA HARBOR CENTER PORT & SERVICES INC',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13174',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13175',
    cwrProcessed: 'eRFP13175',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'MANILA HARBOR CENTER PORT & SERVICES INC',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13175',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13176',
    cwrProcessed: 'eRFP13176',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 02/26/2026 5:32pm',
    remarksCwr: 'LAST PRINT',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'MANILA HARBOR CENTER PORT & SERVICES INC',
    vessel: 'BBC AMBER',
    voy: '1117042',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13176',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13177',
    cwrProcessed: 'eRFP13177',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-05',
    etdTrampsys: '2026-03-07',
    payeePerTrampsys: 'N/A',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'IRASAN - SEAOIL',
    series: '13177',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13178',
    cwrProcessed: 'eRFP13178',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-05',
    etdTrampsys: '2026-03-07',
    payeePerTrampsys: 'ALAN BACAL',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'IRASAN - SEAOIL',
    series: '13178',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13179',
    cwrProcessed: 'eRFP13179',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-05',
    etdTrampsys: '2026-03-07',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'IRASAN - SEAOIL',
    series: '13179',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13180',
    cwrProcessed: 'eRFP13180',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-05',
    etdTrampsys: '2026-03-07',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'IRASAN - SEAOIL',
    series: '13180',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13181',
    cwrProcessed: 'eRFP13181',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-05',
    etdTrampsys: '2026-03-07',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'IRASAN - SEAOIL',
    series: '13181',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13182',
    cwrProcessed: 'eRFP13182',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-06',
    etdTrampsys: '2026-03-08',
    payeePerTrampsys: 'N/A',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'GENERAL SANTOS BULK TERMINAL (SEAOIL)',
    series: '13182',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13183',
    cwrProcessed: 'eRFP13183',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-06',
    etdTrampsys: '2026-03-08',
    payeePerTrampsys: 'PRINCESS SELMA SY',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'GENERAL SANTOS BULK TERMINAL (SEAOIL)',
    series: '13183',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13184',
    cwrProcessed: 'eRFP13184',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-06',
    etdTrampsys: '2026-03-08',
    payeePerTrampsys: 'PHILIPPINE PORT AUTHORITY FAC',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'GENERAL SANTOS BULK TERMINAL (SEAOIL)',
    series: '13184',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13185',
    cwrProcessed: 'eRFP13185',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-06',
    etdTrampsys: '2026-03-08',
    payeePerTrampsys: 'PHILIPPINE PORT AUTHORITY FAC',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'GENERAL SANTOS BULK TERMINAL (SEAOIL)',
    series: '13185',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13186',
    cwrProcessed: 'eRFP13186',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-06',
    etdTrampsys: '2026-03-08',
    payeePerTrampsys: 'PHILIPPINE PORT AUTHORITY FAC',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'GENERAL SANTOS BULK TERMINAL (SEAOIL)',
    series: '13186',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13187',
    cwrProcessed: 'eRFP13187',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-07',
    etdTrampsys: '2026-03-09',
    payeePerTrampsys: 'N/A',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'DAVAO - SEAOIL',
    series: '13187',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13188',
    cwrProcessed: 'eRFP13188',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-07',
    etdTrampsys: '2026-03-09',
    payeePerTrampsys: 'PRINCESS SELMA SY',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'DAVAO - SEAOIL',
    series: '13188',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13189',
    cwrProcessed: 'eRFP13189',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-07',
    etdTrampsys: '2026-03-09',
    payeePerTrampsys: 'PHILIPPINE PORT AUTHORITY FAC',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'DAVAO - SEAOIL',
    series: '13189',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13190',
    cwrProcessed: 'eRFP13190',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-07',
    etdTrampsys: '2026-03-09',
    payeePerTrampsys: 'PHILIPPINE PORT AUTHORITY FAC',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'DAVAO - SEAOIL',
    series: '13190',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13191',
    cwrProcessed: 'eRFP13191',
    cwrUsage: 1,
    trampsysStatus: 'APPROVED',
    statusCwr: 'PRINTED 03/02/2026 9:37am',
    remarksCwr: '',
    etaTrampsys: '2026-03-07',
    etdTrampsys: '2026-03-09',
    payeePerTrampsys: 'PHILIPPINE PORT AUTHORITY FAC',
    vessel: 'LEMAN',
    voy: '26604',
    port: 'DAVAO - SEAOIL',
    series: '13191',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13192',
    cwrProcessed: 'eRFP13192',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-10',
    etdTrampsys: '2026-03-11',
    payeePerTrampsys: 'N/A',
    vessel: 'NXT GENESIS',
    voy: 'VNX80',
    port: 'MANILA SOUTH HARBOR',
    series: '13192',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13195',
    cwrProcessed: 'eRFP13195',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-10',
    etdTrampsys: '2026-03-11',
    payeePerTrampsys: 'IPRUDENTIAL STEVEDORING',
    vessel: 'NXT GENESIS',
    voy: 'VNX80',
    port: 'MANILA SOUTH HARBOR',
    series: '13195',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13196',
    cwrProcessed: 'eRFP13196',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-02-04',
    etdTrampsys: '2026-02-05',
    payeePerTrampsys: 'SUPREME DOMINION CONSOLIDATED',
    vessel: 'SEAFRONTIER',
    voy: '1',
    port: 'GENERAL SANTOS BULK TERMINAL (SEAOIL)',
    series: '13196',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13197',
    cwrProcessed: 'eRFP13197',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-10',
    etdTrampsys: '2026-03-11',
    payeePerTrampsys: 'MICHAEL C. BARBADILLO',
    vessel: 'NXT GENESIS',
    voy: 'VNX80',
    port: 'MANILA SOUTH HARBOR',
    series: '13197',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13198',
    cwrProcessed: 'eRFP13198',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-10',
    etdTrampsys: '2026-03-11',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'NXT GENESIS',
    voy: 'VNX80',
    port: 'MANILA SOUTH HARBOR',
    series: '13198',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13199',
    cwrProcessed: 'eRFP13199',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-10',
    etdTrampsys: '2026-03-11',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'NXT GENESIS',
    voy: 'VNX80',
    port: 'MANILA SOUTH HARBOR',
    series: '13199',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13200',
    cwrProcessed: 'eRFP13200',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-10',
    etdTrampsys: '2026-03-11',
    payeePerTrampsys: 'PHILIPPINE PORTS AUTHORITY',
    vessel: 'NXT GENESIS',
    voy: 'VNX80',
    port: 'MANILA SOUTH HARBOR',
    series: '13200',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13201',
    cwrProcessed: 'eRFP13201',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-26',
    etdTrampsys: '2026-03-27',
    payeePerTrampsys: 'MARVEEN ANGELES',
    vessel: 'ADORA MEDITERRA',
    voy: '0',
    port: 'SUBIC BAY',
    series: '13201',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
  {
    expectedSeries: '13202',
    cwrProcessed: 'eRFP13202',
    cwrUsage: 1,
    trampsysStatus: 'DRAFT',
    statusCwr: '',
    remarksCwr: '',
    etaTrampsys: '2026-03-04',
    etdTrampsys: '2026-03-05',
    payeePerTrampsys: 'MICHAEL C. BARBADILLO',
    vessel: 'BBC AMBER',
    voy: '1117402',
    port: 'MANILA HARBOUR CENTER PORT TERMINAL SERVICES INC',
    series: '13202',
    currencyInCwr: 'PHP',
    amountInCwr: null,
  },
];
