import type { WpsiTransaction } from '../components/WpsiTransactionDetailsPanel';

export const wpsiTransactionsData: WpsiTransaction[] = [
  {
    id: 1,
    label: 'PAYMENT FOR TRUCKING CHARGES /SI: 068260683',
    title: 'FULL BLAST TRUCKING SERVICES',
    amount: '109,739.80',
    section: 'CFII-ACA',
    refNo: 'COTS0326202504808',
    date: '3/26/2025',
    payee: 'FULL BLAST TRUCKING SERVICES',
    particulars: 'PAYMENT FOR TRUCKING CHARGES /SI: 068280683',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04808',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 2,
    label: 'PAYMENT FOR REFUND FOR OVERPAYMENT TO ONE/BL: MNLF17771600',
    title: 'CAROLYN C. DAKIS',
    amount: '2,240.00',
    section: 'CFII-ACA',
    refNo: 'COTS0326202504809',
    date: '3/26/2025',
    payee: 'CAROLYN C. DAKIS',
    particulars: 'PAYMENT FOR REFUND FOR OVERPAYMENT TO ONE/BL: MNLF17771600',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04809',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 3,
    label: 'CONTAINER DEPOSIT / BL NO: JEADVO/2409/1',
    title: 'WEE ENG CONSTRUCTION, INC.',
    amount: '604,500.00',
    section: 'CFII-OL REFUND (PHP)',
    refNo: 'COTS0326202504810',
    date: '3/26/2025',
    payee: 'WEE ENG CONSTRUCTION, INC.',
    particulars: 'CONTAINER DEPOSIT / BL NO: JEADVO/2409/1',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04810',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 4,
    label: 'CONTAINER DEPOSIT 2 / BL NO: JEADVO/2409/1',
    title: 'JOHN SMITH CONSTRUCTION, INC.',
    amount: '604,500.00',
    section: 'CFII-OL REFUND (PHP)',
    refNo: 'COTS0326202504810',
    date: '3/26/2025',
    payee: 'WEE ENG CONSTRUCTION, INC.',
    particulars: 'CONTAINER DEPOSIT / BL NO: JEADVO/2409/1',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04810',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 5,
    label: 'HARBOR FEES / INV: 029381',
    title: 'MANILA HARBOR CENTER PORT SERVICES',
    amount: '34,250.00',
    section: 'CFII-ACA',
    refNo: 'COTS0326202504811',
    date: '3/27/2025',
    payee: 'MANILA HARBOR CENTER PORT SERVICES',
    particulars: 'PAYMENT FOR HARBOR FEES / INV: 029381',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04811',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 6,
    label: 'TUG ASSISTANCE / SOA: 77120',
    title: 'PACIFIC TUG OPERATIONS INC.',
    amount: '76,800.00',
    section: 'CFII-ACA',
    refNo: 'COTS0326202504812',
    date: '3/27/2025',
    payee: 'PACIFIC TUG OPERATIONS INC.',
    particulars: 'PAYMENT FOR TUG ASSISTANCE / SOA: 77120',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04812',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 7,
    label: 'FRESH WATER SUPPLY / DR: 55321',
    title: 'AQUA MARINE UTILITIES',
    amount: '18,950.00',
    section: 'CFII-OL REFUND (PHP)',
    refNo: 'COTS0326202504813',
    date: '3/28/2025',
    payee: 'AQUA MARINE UTILITIES',
    particulars: 'PAYMENT FOR FRESH WATER SUPPLY / DR: 55321',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04813',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  },
  {
    id: 8,
    label: 'SHIP CHANDLER SUPPLIES / INV: 44810',
    title: 'OCEAN CHANDLERY ENTERPRISE',
    amount: '58,430.00',
    section: 'CFII-OL REFUND (PHP)',
    refNo: 'COTS0326202504814',
    date: '3/28/2025',
    payee: 'OCEAN CHANDLERY ENTERPRISE',
    particulars: 'PAYMENT FOR SHIP CHANDLER SUPPLIES / INV: 44810',
    vessel: 'WPSI/PROTANK',
    fundingAccount: 'BDO Check',
    reference: 'PV#04814',
    admin: 'n/a',
    dam: 'Endorsed',
    eya: 'n/a',
    con: 'PENDING'
  }
];