name: cwr_v1_dev

services:
  # --------------------------
  # Redis - Celery Broker
  # --------------------------
  redis:
    build:
      context: ..
      dockerfile: docker_dev/dev.redis.Dockerfile
    container_name: cwr_redis_dev
    restart: always
    volumes:
      - redis_data_dev:/data
    networks:
      - app_network

  # --------------------------
  # Celery Worker
  # --------------------------
  celery_worker:
    build:
      context: ..
      dockerfile: docker_dev/dev.backend.Dockerfile
    container_name: cwr_celery_worker_dev
    working_dir: /app
    command: python3 -m celery -A server.celery:app worker --loglevel=info 
    env_file:
      - ../backend/.env.dev
    environment:
      DB_HOST: db
      ENVIRONMENT: dev
    volumes:
      - ../backend:/app
      - ../media_data:/app/media
    depends_on:
      - db
      - redis
    networks:
      - app_network
    restart: always
  
  # --------------------------
  # Celery Beat (Scheduler)
  # --------------------------
  celery_beat:
    build:
      context: ..
      dockerfile: docker_dev/dev.backend.Dockerfile
    container_name: cwr_celery_beat_dev
    working_dir: /app
    command: python3 -m celery -A server.celery:app beat --loglevel=info --schedule /tmp/celerybeat-schedule
    env_file:
      - ../backend/.env.dev
    environment:
      DB_HOST: db
      ENVIRONMENT: dev
    volumes:
      - ../backend:/app
      - ../media_data:/app/media
    depends_on:
      - db
      - redis
    networks:
      - app_network
    restart: always
    
  # --------------------------
  # Database - MariaDB
  # --------------------------
  db:
    build:
      context: ..
      dockerfile: docker_dev/dev.db.Dockerfile
    image: cwr_v1_dev_mariadb:latest
    container_name: cwr_db_dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: cwr_db
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
      TZ: Asia/Manila 
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -prootpassword --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app_network

  # --------------------------
  # Frontend - React
  # --------------------------
  frontend:
    build:
      context: ..
      dockerfile: docker_dev/dev.frontend.Dockerfile
    container_name: cwr_frontend_dev
    working_dir: /app
    volumes:
      - ../frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app_network
    restart:  unless-stopped

  # --------------------------
  # Backend - Django
  # --------------------------
  backend:
    build:
      context: ..
      dockerfile: docker_dev/dev.backend.Dockerfile
    env_file:
      - ../backend/.env.dev
    container_name: cwr_backend_dev
    environment:
      DB_HOST: db   # override host for Docker
      ENVIRONMENT: dev
    command: sh -c "python3 manage.py migrate --noinput; python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - ../media_data:/app/media
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always

  # --------------------------
  # Proxy Server - Nginx
  # --------------------------
  proxy:
    build:
      context: ..
      dockerfile: docker_dev/dev.nginx.Dockerfile
    container_name: cwr_proxy_dev
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge

volumes:
  node_modules_cache:
  db_data_dev:
  redis_data_dev:
